#!/bin/bash
# TempoNest Environment Setup
# Generated by build_temponest.sh on Sun Jun 29 04:59:31 PM CEST 2025
# Source this file before using TempoNest: source ./temponest_env.sh

# ===== TempoNest Dependencies =====
export MULTINEST_DIR="/home/aparthas/software/sources/GPU_Timing/TempoNest/external/MultiNest"
export LD_LIBRARY_PATH="/home/aparthas/software/sources/GPU_Timing/TempoNest/external/MultiNest:$LD_LIBRARY_PATH"
export POLYCHORD_DIR="/home/aparthas/software/sources/GPU_Timing/TempoNest/external/PolyChordLite"
export LD_LIBRARY_PATH="/home/aparthas/software/sources/GPU_Timing/TempoNest/external/PolyChordLite/lib:$LD_LIBRARY_PATH"
export ARRAYFIRE_PATH="/home/aparthas/software/sources/GPU_Timing/TempoNest/external/ArrayFire"
export LD_LIBRARY_PATH="/home/aparthas/software/sources/GPU_Timing/TempoNest/external/ArrayFire/lib64:/home/aparthas/software/sources/GPU_Timing/TempoNest/external/ArrayFire/lib:$LD_LIBRARY_PATH"
export TEMPO2="/home/aparthas/software/apps/tempo2"
export PATH="/home/aparthas/software/apps/tempo2/bin:$PATH"
export LD_LIBRARY_PATH="/home/aparthas/software/apps/tempo2/lib:$LD_LIBRARY_PATH"

# Remove duplicate entries from LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$(echo "$LD_LIBRARY_PATH" | tr ':' '\n' | awk '!seen[$0]++' | tr '\n' ':' | sed 's/:$//')

# ===== Status Messages =====
echo "==============================================="
echo "TempoNest Environment Loaded"
echo "==============================================="
echo "TEMPO2: $TEMPO2"
echo "MULTINEST_DIR: $MULTINEST_DIR"
echo "POLYCHORD_DIR: $POLYCHORD_DIR"
echo "ARRAYFIRE_PATH: $ARRAYFIRE_PATH"
echo "LD_LIBRARY_PATH configured for runtime"
echo "==============================================="
echo "Available samplers: MultiNest, PolyChord"
echo "You can now run: tempo2 -gr temponest ..."
echo "==============================================="
